#!/usr/bin/env python3.6
# -*- coding: utf-8 -*-

from socket import *
import threading
import time

def output(arg):
    while True:
        time.sleep(2)
        print('thread number: %d run'%arg)

for i in range(5):
    thread=threading.Thread(target=output,args=(i,))
    thread.start()
print('Create of threads finish')

